log:
  level: info
  path:  /app/logs/${container_id:${HOSTNAME:localhost}}

server:
  servlet:
    context-path: /
  port: ${server_port:8005}
spring:
  application:
    name: service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://${db_host:192.168.2.52}:${db_port:3306}/${db_name:project07}?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: ${db_user:project07}
    password: ${db_password:project07}
    hikari:
      max-lifetime: 28800
      connection-timeout: 30000
      idle-timeout:  600000
      maximum-pool-size:  50
      minimum-idle: 1

mybatis-plus:
  #config-location: classpath:mapper-config.xml mybatis配置文件
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.hfjy.student.bean.domain
  global-config:
    db-config:
      db-type: mysql
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID" 参见com.baomidou.mybatisplus.annotation.IdType;
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"0
      field-strategy: NOT_EMPTY
      #数据库大写下划线转换
      #capital-mode: true
    #刷新mapper 调试神器
    #refresh: true
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
